service: khalics

# custom:
  # env: ${file(./${self:provider.stage}.env.json)}

package:
  individually: true
  exclude:
    - ./**
  include:
    - dev.env.json

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-west-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:eu-west-1:*:*"
    - Effect: Allow
      Action:
        - cognito-idp:ListUsers
      Resource: "arn:aws:cognito-idp:eu-west-1:458723785925:userpool/eu-west-1_jrpxZzyiw"
plugins:
  - serverless-offline

functions:
  ##user##
  # user create
  postConfirmCognitoTrigger:
    handler: services/user/postConfirmCognitoTrigger/index.handler
    events:
     - http:
         path: /user/postConfirmCognitoTrigger
         method: post
         cors: true
    package:
      include:
        - services/lib/fieldVerif.js
        - services/user/postConfirmCognitoTrigger/index.js
        - services/user/postConfirmCognitoTrigger/node_modules/**

  getUser:
    handler: services/user/get/index.handler
    events:
     - http:
         path: /user/get
         method: get
         cors: true
         authorizer:
           name: authorizerUserPool
           arn: arn:aws:cognito-idp:eu-west-1:458723785925:userpool/eu-west-1_jrpxZzyiw
    package:
      include:
        - services/user/get/index.js
        - services/user/get/node_modules/**

  ##workout##
  getWorkout:
    handler: services/workout/get/index.handler
    events:
      - http:
          path: /workout/get
          method: get
          cors: true
    package:
      include:
        - services/workout/get/index.js
        - services/workout/get/node_modules/**

  createWorkout:
    handler: services/workout/create/index.handler
    events:
      - http:
          path: /workout/create
          method: post
          cors: true
    package:
      include:
        - services/lib/fieldVerif.js
        - services/workout/create/index.js
        - services/workout/create/node_modules/**

  ##exercise##
  createExercise:
    handler: services/exercise/create/index.handler
    events:
      - http:
          path: /exercise/create
          method: post
          cors: true
    package:
      include:
        - services/lib/fieldVerif.js
        - services/exercise/create/index.js
        - services/exercise/create/node_modules/**

  getExercise:
    handler: services/exercise/get/index.handler
    events:
      - http:
          path: /exercise/get
          method: get
          cors: true
    package:
      include:
        - services/lib/fieldVerif.js
        - services/exercise/get/index.js
        - services/exercise/get/node_modules/**