service: khalics

custom:
  env: ${file(./${self:provider.stage}.env.json)}

package:
  individually: true
  exclude:
    - ./**
  include:
    - dev.env.json

provider:
  name: aws
  vpc:
    securityGroupIds:
      - sg-09637a881a2425673
    subnetIds:
      - subnet-62ed8d2a
      - subnet-2d1bc977
      - subnet-e1ef7f87
  runtime: nodejs8.10
  stage: dev
  region: eu-west-1
  environment:
    DB_HOST: ${self:custom.env.DB_HOST}
    DB_USER: ${self:custom.env.DB_USER}
    DB_PASSWORD: ${self:custom.env.DB_PASSWORD}

functions:
  create:
    handler: services/user/create/index.handler
    events:
     - http:
         path: /user/create
         method: post
    package:
      include:
        - services/user/create/index.js
        - services/lib/node_modules/**
        - services/lib/dbInit.js
