service: lambda-test # NOTE: update this with your service name

provider:
  name: aws
  vpc:
    securityGroupIds:
      - sg-09637a881a2425673
    subnetIds:
      - subnet-62ed8d2a
      - subnet-2d1bc977
      - subnet-e1ef7f87
  runtime: nodejs8.10
  # you can overwrite defaults here
  # stage: dev
  region: eu-west-1
  environment:
    dbHost: ${env:KHALICS_DB_HOST}
    dbUser: ${env:KHALICS_DB_USER}
    dbPassword: ${env:KHALICS_DB_PASSWORD}
functions:
  userCreate:
    handler: handler.userCreate
    vpc:
      securityGroupIds:
        - sg-09637a881a2425673
      subnetIds:
        - subnet-62ed8d2a
        - subnet-2d1bc977
        - subnet-e1ef7f87
    events:
     - http:
         path: /user/create
         method: post
  test:
    handler: handler.test
    events:
     - http:
         path: /test
         method: get
    environment:
      TEST_API_KEY: key4242
