service: khalics

# custom:
  # env: ${file(../../${self:provider.stage}.env.json)}

provider:
  name: aws
  vpc:
    securityGroupIds:
      - sg-09637a881a2425673
    subnetIds:
      - subnet-62ed8d2a
      - subnet-2d1bc977
      - subnet-e1ef7f87
  runtime: nodejs8.10
  stage: dev
  region: eu-west-1
  # environment:
  #   dbHost: ${self:custom.env.DB_HOST}
  #   dbUser: ${self:custom.env.DB_USER}
  #   dbPassword: ${self:custom.env.DB_PASSWORD}

functions:
  create:
    handler: create.create
    events:
     - http:
         path: /user/create
         method: post
